#Andre Barrientos
#PID: 5443095
#Makefile to compile and execute programs.
CC = gcc
FILES = poker.c pokerMain.c
OUT_EXEC = poker.out

build:	$(FILES)
	$(CC) -o $(OUT_EXEC) $(FILES)

clean:
	rm -f *.o core
